#! /bin/sh
# /etc/init.d/brimud
#

export BRIMUD_HOME=./

# Some things that run always
touch /var/lock/brimud

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script brimud "
    java -jar $BRIMUD_HOME/brimud.jar &
    echo $! > $BRIMUD_HOME/brimud.pid
    ;;
  stop)
    echo "Stopping script brimud"
    kill `cat $BRIMUD_HOME/brimud.pid`
    rm $BRIMUD_HOME/brimud.pid
    ;;
  *)
    echo "Usage: /etc/init.d/brimud {start|stop}"
    exit 1
    ;;
esac
